/* graph-data.js
   Research knowledge graph data, exposed as a global variable
   so it works on both file:// and HTTP origins without CORS issues.
*/
window.GRAPH_DATA = {
    "nodes": [
        {
            "id": "Stellar-mass Black Holes",
            "group": "Core Topic",
            "description": "Compact remnants of massive stars, central to the study of dynamical interactions and structural evolution in dense stellar environments."
        },
        {
            "id": "Star Clusters",
            "group": "Astrophysical Environments",
            "description": "Dense stellar environments (such as globular and young massive clusters) that host high rates of dynamical encounters and act as primary channels for black hole mergers."
        },
        {
            "id": "Supernovae",
            "group": "Stellar Physics",
            "description": "Explosive deaths of massive stars that lead to the formation of compact remnants, including black holes and neutron stars."
        },
        {
            "id": "Natal Kicks",
            "group": "Stellar Physics",
            "description": "Velocity kicks imparted onto black holes and neutron stars during their formation in supernovae due to asymmetric mass ejection or neutrino emission."
        },
        {
            "id": "Black Hole Retention",
            "group": "Theoretical Frameworks",
            "description": "The fraction of black holes that remain gravitationally bound to their host star cluster after receiving natal kicks, heavily influencing the cluster's long-term dynamics."
        },
        {
            "id": "Binary Black Holes (BBHs)",
            "group": "Core Topic",
            "description": "Systems of two black holes orbiting each other, which can eventually inspiral and merge due to the emission of gravitational radiation."
        },
        {
            "id": "Dynamical Formation Channel",
            "group": "Theoretical Frameworks",
            "description": "The assembly of binary black holes through gravitational interactions (e.g., three-body encounters) in dense star clusters."
        },
        {
            "id": "Gravitational Waves (GWs)",
            "group": "Observational Astrophysics",
            "description": "Ripples in spacetime generated by accelerating massive objects, most notably coalescing binary black holes and neutron stars."
        },
        {
            "id": "GW Detectors",
            "group": "Observational Instruments",
            "description": "A global network of ground-based interferometers designed to detect gravitational waves from compact object mergers."
        },
        {
            "id": "N-body Simulations",
            "group": "Computational Methods",
            "description": "Advanced numerical codes (e.g., NBODY6, MOCCA, CMC) used to model the complex, long-term gravitational interactions and stellar evolution within star clusters."
        },
        {
            "id": "Massive Stars",
            "group": "Stellar Physics",
            "description": "Progenitor stars with significant mass whose evolutionary tracks, mass loss, and final core collapses dictate the initial mass function of black holes."
        },
        {
            "id": "Pair-Instability",
            "group": "Stellar Physics",
            "description": "A disruption mechanism in very massive stars caused by electron-positron pair production, leading to pulsational mass loss or complete supernovae, creating an upper mass gap in the black hole population."
        },
        {
            "id": "Intermediate-Mass Black Holes (IMBHs)",
            "group": "Core Topic",
            "description": "Black holes significantly more massive than stellar-mass black holes but lighter than supermassive ones, potentially formed through runaway stellar collisions or hierarchical mergers in clusters."
        },
        {
            "id": "Isolated Binary Evolution",
            "group": "Theoretical Frameworks",
            "description": "The formation of binary black holes from isolated pairs of massive stars that evolve together without the influence of dense external dynamical environments."
        },
        {
            "id": "Active Galactic Nuclei (AGN)",
            "group": "Core Topic",
            "description": "Intensely luminous compact regions at the centers of galaxies, powered by accreting supermassive black holes, whose radiant emissions can outshine their host galaxies."
        },
        {
            "id": "Supermassive Black Holes (SMBHs)",
            "group": "Core Topic",
            "description": "Extremely massive black holes residing at the centers of most massive galaxies, driving AGN activity and co-evolving with their host galaxies."
        },
        {
            "id": "Galaxies",
            "group": "Astrophysical Environments",
            "description": "The cosmic structures containing stars, gas, and dust that harbor central supermassive black holes and can be classified as star-forming or quiescent."
        },
        {
            "id": "Galaxy Evolution",
            "group": "Theoretical Frameworks",
            "description": "The long-term changes in galaxy properties, star formation, and morphology, fundamentally linked to the growth and feedback of central SMBHs."
        }
    ],
    "links": [
        {
            "source": "Massive Stars",
            "target": "Supernovae",
            "label": "end lives as",
            "inferred": false
        },
        {
            "source": "Supernovae",
            "target": "Stellar-mass Black Holes",
            "label": "produce",
            "inferred": false
        },
        {
            "source": "Supernovae",
            "target": "Natal Kicks",
            "label": "impart",
            "inferred": false
        },
        {
            "source": "Natal Kicks",
            "target": "Black Hole Retention",
            "label": "influence",
            "inferred": false
        },
        {
            "source": "Black Hole Retention",
            "target": "Star Clusters",
            "label": "determines population within",
            "inferred": false
        },
        {
            "source": "Star Clusters",
            "target": "Dynamical Formation Channel",
            "label": "act as primary environment for",
            "inferred": false
        },
        {
            "source": "Stellar-mass Black Holes",
            "target": "Star Clusters",
            "label": "governs structural evolution of",
            "inferred": false
        },
        {
            "source": "Stellar-mass Black Holes",
            "target": "Binary Black Holes (BBHs)",
            "label": "form",
            "inferred": false
        },
        {
            "source": "Dynamical Formation Channel",
            "target": "Binary Black Holes (BBHs)",
            "label": "drives production of",
            "inferred": false
        },
        {
            "source": "Isolated Binary Evolution",
            "target": "Binary Black Holes (BBHs)",
            "label": "acts as competing formation channel for",
            "inferred": true
        },
        {
            "source": "Binary Black Holes (BBHs)",
            "target": "Gravitational Waves (GWs)",
            "label": "emit during merger",
            "inferred": false
        },
        {
            "source": "Gravitational Waves (GWs)",
            "target": "GW Detectors",
            "label": "observed via",
            "inferred": false
        },
        {
            "source": "N-body Simulations",
            "target": "Star Clusters",
            "label": "model dynamics of",
            "inferred": false
        },
        {
            "source": "N-body Simulations",
            "target": "Black Hole Retention",
            "label": "used to place constraints on",
            "inferred": true
        },
        {
            "source": "Massive Stars",
            "target": "Pair-Instability",
            "label": "constrained by",
            "inferred": false
        },
        {
            "source": "Pair-Instability",
            "target": "Stellar-mass Black Holes",
            "label": "limits remnant masses of",
            "inferred": false
        },
        {
            "source": "Dynamical Formation Channel",
            "target": "Intermediate-Mass Black Holes (IMBHs)",
            "label": "can assemble via hierarchical mergers",
            "inferred": true
        },
        {
            "source": "Active Galactic Nuclei (AGN)",
            "target": "Supermassive Black Holes (SMBHs)",
            "label": "powered by",
            "inferred": false
        },
        {
            "source": "Supermassive Black Holes (SMBHs)",
            "target": "Galaxies",
            "label": "co-evolve with",
            "inferred": false
        },
        {
            "source": "Active Galactic Nuclei (AGN)",
            "target": "Galaxies",
            "label": "outshine and contaminate light of",
            "inferred": false
        },
        {
            "source": "Galaxies",
            "target": "Galaxy Evolution",
            "label": "undergo",
            "inferred": false
        },
        {
            "source": "Supermassive Black Holes (SMBHs)",
            "target": "Intermediate-Mass Black Holes (IMBHs)",
            "label": "are the more massive counterparts to",
            "inferred": true
        },
        {
            "source": "Supermassive Black Holes (SMBHs)",
            "target": "Stellar-mass Black Holes",
            "label": "represent the upper mass extreme compared to",
            "inferred": true
        },
        {
            "source": "Galaxy Evolution",
            "target": "Star Clusters",
            "label": "encompasses the formation and dynamics of",
            "inferred": true
        },
        {
            "source": "Supernovae",
            "target": "Galaxy Evolution",
            "label": "drive chemical enrichment and feedback in",
            "inferred": true
        },
        {
            "source": "Active Galactic Nuclei (AGN)",
            "target": "Massive Stars",
            "label": "feedback mechanisms can quench or trigger formation of",
            "inferred": true
        }
    ]
};
